strictdoc-project/strictdoc

- strictdoc/export/html/templates/_shared/table_of_contents.jinja.html
> export/html: Makes empty TOC container visible on all pages

- strictdoc/export/html/static/global.css
> export/html: Fix table view

- strictdoc/export/html/static/single_document_table.css
> export/html: Fix table view (media queries)

- strictdoc/export/html/static/layout-main-with-toc.css
- strictdoc/export/html/static/single_document_table.css
- strictdoc/export/html/static/toc.js
- strictdoc/export/html/templates/_shared/table_of_contents.jinja.html
- strictdoc/export/html/templates/single_document/document.jinja.html
- strictdoc/export/html/templates/single_document_table/document.jinja.html
- strictdoc/export/html/templates/single_document_traceability/document.jinja.html
- strictdoc/export/html/templates/single_document_traceability_deep/document.jinja.html
> Make TOC closable

- strictdoc/export/html/static/global.css
- strictdoc/export/html/static/layout-main-with-toc.css
- strictdoc/export/html/templates/single_document/document.jinja.html
> export/html: fix margins for P and UL

- strictdoc/export/html/static/global.css
> export/html: Document page: styles for <blockquote>

- .gitignore
- strictdoc/export/html/static/global.css
- strictdoc/export/html/static/single_document_traceability.css
- strictdoc/export/html/templates/_shared/requirement.jinja.html
- strictdoc/export/html/templates/_shared/requirement_card.jinja.html
- strictdoc/export/html/templates/single_document/document.jinja.html
- strictdoc/export/html/templates/single_document_table/requirement.jinja.html
- strictdoc/export/html/templates/single_document_traceability/document.jinja.html
- strictdoc/export/html/templates/single_document_traceability_deep/document.jinja.html
> export/html: Unify Requirements partials (except tables)

- strictdoc/export/html/static/global.css
- strictdoc/export/html/static/single_document_table.css
- strictdoc/export/html/templates/_shared/requirement.jinja.html
- strictdoc/export/html/templates/single_document_table/document.jinja.html
Check if this view is suitable.
If yes, the file single_document_table.css is obsolete.
> view-table on flex

- strictdoc/backend/dsl/grammar.py
- strictdoc/backend/dsl/models.py
- strictdoc/core/traceability_index.py
- tests/unit/cli/test_cli_arg_parser.py
> grammar: make sure that the UID field is either a value or None

- strictdoc/export/html/static/document_tree.css
- strictdoc/export/html/static/global.css
- strictdoc/export/html/static/layout-main-with-toc.css
- strictdoc/export/html/templates/_shared/table_of_contents.jinja.html
- strictdoc/export/html/templates/single_document/document.jinja.html
- strictdoc/export/html/templates/single_document_table/document.jinja.html
- strictdoc/export/html/templates/single_document_traceability/document.jinja.html
- strictdoc/export/html/templates/single_document_traceability_deep/document.jinja.html
Here, so far, only an imitation of links, due to the fact that the URLs are still generated incorrectly
> export/html: Add TOC bar with pseudo-links

- strictdoc/export/html/templates/single_document/document.jinja.html
- strictdoc/export/html/templates/single_document_table/document.jinja.html
- strictdoc/export/html/templates/single_document_traceability/document.jinja.html
- strictdoc/export/html/templates/single_document_traceability_deep/document.jinja.html
- tests/integration/html_markup_validator.py
- tests/integration/lit.cfg
- tests/integration/self-testing/commands/export/01-strictdoc-smoke-test/test.itest
>  export/html: resolve remaining HTML/XML markup errors + integration test 

- .github/workflows/ci-mac.yml
- strictdoc/backend/dsl/reader.py
- strictdoc/cli/main.py
> CI: Python 3.8-related fixes for macOS

- strictdoc/export/html/static/global.css
- strictdoc/export/html/static/layout-main-with-toc.css
- strictdoc/export/html/templates/_shared/requirement.jinja.html
- strictdoc/export/html/templates/_shared/table_of_contents.jinja.html
- strictdoc/export/html/templates/single_document/document.jinja.html
- strictdoc/export/html/templates/single_document_table/document.jinja.html
- strictdoc/export/html/templates/single_document_traceability/document.jinja.html
> export/html: TOC and titles

- strictdoc/export/html/static/global.css
- strictdoc/export/html/templates/_shared/requirement.jinja.html
> export/html: print requirement parents

- strictdoc/export/html/templates/_shared/table_of_contents.jinja.html
> export/html: fix TOC

- strictdoc/export/html/static/global.css
- strictdoc/export/html/templates/single_document_table/document.jinja.html
> export/html: fix tables template (remove sections and add sticky headers)

- docs/sphinx/source/StrictDoc.rst
- strictdoc/export/rst/export.py
- strictdoc/export/rst/writer.py
> export/rst: do not generate top-level header if single document tree

- strictdoc/core/document_finder.py
- strictdoc/core/document_meta.py
- strictdoc/core/document_tree.py
- tests/integration/commands/export/05_input_is_single_file/input.sdoc
- tests/integration/commands/export/05_input_is_single_file/test.itest
> export/html: enable passing single files as input

- docs/sphinx/source/StrictDoc.rst
- strictdoc/export/rst/export.py
- strictdoc/export/rst/writer.py
- tasks.py
> export/rst: print parent and child links

- strictdoc/core/document_meta.py
- strictdoc/export/html/renderers/link_renderer.py
- strictdoc/export/html/templates/_shared/requirement.jinja.html
- strictdoc/export/html/templates/single_document/document.jinja.html
- strictdoc/export/html/templates/single_document_table/document.jinja.html
- strictdoc/export/html/templates/single_document_traceability/document.jinja.html
- strictdoc/export/html/templates/single_document_traceability_deep/document.jinja.html
- strictdoc/export/html/templates/single_document_traceability_deep/recursive_cell_children.jinja.html
- strictdoc/export/html/templates/single_document_traceability_deep/recursive_cell_parent.jinja.html
> export/html: requirements' hyperlinks are implemented consistently

- strictdoc/backend/dsl/models/requirement.py
- strictdoc/backend/dsl/models/section.py
- strictdoc/backend/dsl/reader.py
- strictdoc/export/html/_static/_layout.css
- strictdoc/export/html/document_type.py
- strictdoc/export/html/generators/document.py
- strictdoc/export/html/generators/document_deep_trace.py
- strictdoc/export/html/generators/document_table.py
- strictdoc/export/html/generators/document_trace.py
- strictdoc/export/html/templates/_shared/toc.jinja.html
- strictdoc/export/html/templates/single_document_traceability_deep/document.jinja.html
> export/html: DTR: display sections that have requirements

- strictdoc/helpers/parallelizer.py
Python Multiprocessing: Crash in subprocess?
https://stackoverflow.com/questions/24894682/python-multiprocessing-crash-in-subprocess/24894997#24894997
Closes #313
> parallelizer: fix hanging and zombie processes when child processes misbehave

- strictdoc/core/document_finder.py
- strictdoc/core/document_tree.py
- tests/integration/commands/export/07_input_is_single_file/test.itest
- tests/integration/commands/export/html/assets/02_asset_export_single_sdoc_rel_path/_assets/sandbox1.svg
- tests/integration/commands/export/html/assets/02_asset_export_single_sdoc_rel_path/input.sdoc
- tests/integration/commands/export/html/assets/02_asset_export_single_sdoc_rel_path/test.itest
- tests/integration/commands/export/html/assets/03_asset_export_single_sdoc_full_path/_assets/sandbox1.svg
- tests/integration/commands/export/html/assets/03_asset_export_single_sdoc_full_path/input.sdoc
- tests/integration/commands/export/html/assets/03_asset_export_single_sdoc_full_path/test.itest
> export/html: fix the generation of assets for a single file case

- strictdoc/export/html/renderers/link_renderer.py
- tests/integration/commands/export/html/file_traceability/01_basic_req_to_file_link_full_path/test.itest
- tests/integration/commands/export/html/file_traceability/02_basic_req_to_file_link_cwd_dot/test.itest
- tests/integration/commands/export/html/file_traceability/04_input_is_single_file/test.itest
- tests/integration/commands/export/html/file_traceability/05_multiple_files_per_requirement/test.itest
> export/html: Sec and Req anchors section number to ensure link uniqueness

- .pylint.ini
- strictdoc/core/traceability_index.py
> traceability: fix the missing source file and requirement warnings

- strictdoc/export/html/_static/_element.css
- strictdoc/export/html/_static/_requirement-tree.css
- strictdoc/export/html/_static/_source.css
- strictdoc/export/html/_static/source-code-coverage.js
- strictdoc/export/html/templates/_shared/docsection.jinja.html
- strictdoc/export/html/templates/_shared/requirement.jinja.html
- strictdoc/export/html/templates/_shared/requirement_block/ancor.jinja.html
- strictdoc/export/html/templates/_shared/requirement_block/comment.jinja.html
- strictdoc/export/html/templates/_shared/requirement_block/files_list.jinja.html
- strictdoc/export/html/templates/_shared/requirement_block/files_tree.jinja.html
- strictdoc/export/html/templates/_shared/requirement_block/free_text.jinja.html
- strictdoc/export/html/templates/_shared/requirement_block/h_title.jinja.html
- strictdoc/export/html/templates/_shared/requirement_block/meta.jinja.html
- strictdoc/export/html/templates/_shared/requirement_block/rationale.jinja.html
- strictdoc/export/html/templates/_shared/requirement_block/related.jinja.html
- strictdoc/export/html/templates/_shared/requirement_block/statement.jinja.html
- strictdoc/export/html/templates/_shared/requirement_block/uid_and_title.jinja.html
- strictdoc/export/html/templates/requirements_coverage/requirement.jinja.html
- strictdoc/export/html/templates/source_file_view/source_file_view.jinja.html
- strictdoc/export/html/templates/source_file_view/source_refer.jinja.html
- strictdoc/export/html/templates/source_file_view/source_requirement.jinja.html
- tests/integration/commands/export/html/file_traceability/03_basic_req_to_file_link_range/test.itest
- micro requirement blocks, 
- make source-file menu use file-tree, 
- move toggle switch 'Show coverage' into Ranges menu block
> export/html: update source-file-view, use micro requirement blocks

- strictdoc/core/file_tree.py
until a general solution is found by #456
> export/html: ignore "tests" when looking for _assets for now

- strictdoc/backend/dsl/grammar.py
- strictdoc/backend/dsl/models/document.py
- strictdoc/backend/dsl/models/document_config.py
- strictdoc/backend/dsl/writer.py
- strictdoc/export/html/generators/document.py
- strictdoc/export/html/generators/document_deep_trace.py
- strictdoc/export/html/generators/document_table.py
- strictdoc/export/html/generators/document_trace.py
- strictdoc/export/html/generators/requirements_coverage.py
- strictdoc/export/html/generators/source_file_view_generator.py
- strictdoc/export/html/renderers/markup_renderer.py
- strictdoc/export/html/renderers/text_to_html_writer.py
- tests/integration/commands/export/html/per_document_options/option_markup/01_options_markup_is_default/input.sdoc
- tests/integration/commands/export/html/per_document_options/option_markup/01_options_markup_is_default/test.itest
- tests/integration/commands/export/html/per_document_options/option_markup/02_options_markup_is_text/input.sdoc
- tests/integration/commands/export/html/per_document_options/option_markup/02_options_markup_is_text/test.itest
- tests/unit/dsl/test_dsl_passthrough.py
- tests/unit/helpers/test_document_builder.py
- tests/unit/strictdoc/export/html/renderers/test_text_to_html_fragment_writer.py
Closes #465
No documentation yet during the testing period.
> grammar: document-level option to specify markup (RST and Text for now)

- strictdoc/backend/dsl/models/requirement.py
- strictdoc/backend/dsl/writer.py
- strictdoc/helpers/lxml.py
- strictdoc/imports/reqif/stage1/models/reqif_bundle.py
- strictdoc/imports/reqif/stage1/parsers/spec_object_parser.py
- strictdoc/imports/reqif/stage2/doors/mapping.py
- strictdoc/imports/reqif/stage2/doors/parser.py
- strictdoc/imports/reqif/stage2/doors/uid_matcher.py
- tests/integration/reqif/90_doors_SUBSET-026-3-v330/test.itest
- tests/unit/strictdoc/helpers/test_lxml.py
- tests/unit/strictdoc/import/reqif/stage2/doors/test_uid_matcher.py
Also parse subrequirements a) b) c) ..., add them to their parent
simply as text for now.
> import/reqif: Doors parser: parse tables stored as XHTML fields

- Dockerfile
> add Dockerfile for dockerization of strictdoc

- strictdoc/backend/reqif/export/sdoc_to_reqif_converter.py
- strictdoc/backend/reqif/sdoc_reqif_fields.py
NOTE: this requires changes in the reqif library as well!
> Capella compatiblity

- .gitignore
- strictdoc/backend/sdoc/error_handling.py
- strictdoc/backend/sdoc/models/type_system.py
- strictdoc/backend/sdoc/validations/requirement.py
- tests/integration/per_document_grammar/03_non_required_grammar_fields_are_skipped/input.sdoc
- tests/integration/per_document_grammar/03_non_required_grammar_fields_are_skipped/test.itest
- tests/integration/per_document_grammar/validation/04_missing_required_grammar_field/test.itest
> backend/sdoc: custom grammar: fix an unimplemented aspect

- .github/workflows/check-dead-links.yml
- tasks.py
- tools/link_health.py
> link_health: check dead links in strict.sdoc

- .github/workflows/periodic-check-dead-links.yml
- .github/workflows/periodic-integration-test.yml
> CI: daily integration test

- strictdoc/backend/sdoc/models/type_system.py
- strictdoc/backend/sdoc/validations/requirement.py
- tests/integration/per_document_grammar/validation/05_unexpected_field_outside_grammar/test.itest
> bugfix: AttributeError: 'NoneType' object has no attribute 'required'

- .github/workflows/periodic-integration-test.yml
- .gitignore
- strictdoc/cli/cli_arg_parser.py
- strictdoc/core/traceability_index_builder.py
- strictdoc/export/html/generators/document.py
- strictdoc/export/html/generators/document_deep_trace.py
- strictdoc/export/html/generators/document_table.py
- strictdoc/export/html/generators/document_trace.py
- strictdoc/export/html/generators/document_tree.py
- strictdoc/export/html/generators/requirements_coverage.py
- strictdoc/export/html/generators/source_file_coverage.py
- strictdoc/export/html/generators/source_file_view_generator.py
- strictdoc/export/html/html_generator.py
- strictdoc/export/html/html_templates.py
- tasks.py
>  tasks: enable installation using PyInstaller 

- strictdoc/backend/reqif/export/sdoc_to_reqif_converter.py
- strictdoc/backend/sdoc/models/document_grammar.py
- strictdoc/backend/sdoc/models/object_factory.py
- strictdoc/backend/sdoc/models/requirement.py
- strictdoc/backend/sdoc/models/type_system.py
- strictdoc/backend/sdoc/validations/requirement.py
- strictdoc/backend/sdoc/writer.py
- strictdoc/core/traceability_index_builder.py
- tests/unit/strictdoc/backend/sdoc/test_requirement_from_dict.py
Separated part 1 Replacing strings.
See Discussions #741 GrammarElementField-TypeValue and External-Refs
Thx,
Guus
> Use constants instead of hardcoded Requirement-Fieldname strings.

- docs/sphinx/source/strictdoc_01_user_guide.rst
- docs/strictdoc_01_user_guide.sdoc
docs:strictdoc_01_user_guide UGuide updates/restructuring for new Document.Classification field, redefined Requirement-References and ReferenceType variants, adding docs for all Document and Requirement fields.
> docs:strictdoc_01_user_guide UGuide updates/restructuring

- docs/strictdoc_21_design.sdoc
- strictdoc/backend/reqif/export/sdoc_to_reqif_converter.py
- strictdoc/backend/reqif/import_/reqif_to_sdoc_converter.py
- tests/integration/backend/reqif/native/end_to_end/14_document_freetext/sample.sdoc
- tests/integration/backend/reqif/native/end_to_end/14_document_freetext/test.itest
> backend/reqif: exporting document's free text

- docs/strictdoc_04_backlog.sdoc
- strictdoc/export/html/form_objects/document_form_object.py
- strictdoc/export/html/form_objects/requirement_form_object.py
- strictdoc/export/html/form_objects/section_form_object.py
- strictdoc/server/controllers/main_controller.py
- tests/end2end/document/02_editing_document_free_text/uc02_04_escape_html/document.expected.sdoc
- tests/end2end/document/02_editing_document_free_text/uc02_04_escape_html/document.sdoc
- tests/end2end/document/02_editing_document_free_text/uc02_04_escape_html/test_uc02_04_escape_html.py
- tests/end2end/document/07_editing_requirement/uc07_04_escape_html/document.expected.sdoc
- tests/end2end/document/07_editing_requirement/uc07_04_escape_html/document.sdoc
- tests/end2end/document/07_editing_requirement/uc07_04_escape_html/test_uc07_04_escape_html.py
- tests/end2end/document/08_edit_section/10_editing_section_escaping_html/document.expected.sdoc
- tests/end2end/document/08_edit_section/10_editing_section_escaping_html/document.sdoc
- tests/end2end/document/08_edit_section/10_editing_section_escaping_html/test_10_editing_section_escaping_html.py
> server: escape multi-line text when rendering edit forms (requirement, section)

- strictdoc/export/html/html_generator.py
- strictdoc/export/rst/rst_to_html_fragment_writer.py
- tests/end2end/server.py
> server: fix zombie worker processes issue when Selenium timeouts

- strictdoc/export/rst/templates/requirement.jinja.rst
- tests/integration/commands/export/rst/08_custom_field/expected/input.rst
- tests/integration/commands/export/rst/08_custom_field/input.sdoc
- tests/integration/commands/export/rst/08_custom_field/test.itest
> export, rst: add custom grammar fields into jinja2 rendering

- requirements.txt
- strictdoc/backend/excel/export/excel_generator.py
- strictdoc/backend/excel/import_/excel_to_sdoc_converter.py
- strictdoc/backend/reqif/export/sdoc_to_reqif_converter.py
- strictdoc/backend/reqif/import_/reqif_to_sdoc_factory.py
- strictdoc/backend/sdoc/grammar/type_system.py
- strictdoc/backend/sdoc/models/constants.py
- strictdoc/backend/sdoc/models/reference.py
- strictdoc/backend/sdoc/models/requirement.py
- strictdoc/backend/sdoc/models/type_system.py
- strictdoc/backend/sdoc/writer.py
- strictdoc/core/file_traceability_index.py
- strictdoc/core/traceability_index_builder.py
- strictdoc/export/html/renderers/link_renderer.py
- strictdoc/export/html/templates/_shared/requirement_block/files_list.jinja.html
- strictdoc/export/html/templates/_shared/requirement_block/files_tree.jinja.html
- strictdoc/export/html/templates/_shared/requirement_table.jinja.html
- strictdoc/export/html/templates/single_document_table/document.jinja.html
- strictdoc/export/html/templates/source_file_view/source_requirement.jinja.html
- strictdoc/export/rst/templates/requirement.jinja.rst
- strictdoc/export/rst/writer.py
- tests/integration/per_document_grammar/validation/06_gef_reference_type_not_allowed/test.itest
- tests/unit/helpers/test_document_builder.py
- tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough.py
First step: Refactoring existing REFS
> backend/sdoc/grammar: Refactoring REFS ParentReqReference, FileReference

- tasks.py
> tasks: adapt PyInstaller to support "strictdoc server" command

- examples/example_08.sdoc
- examples/example_source_files/file2.py
- strictdoc/export/html/generators/source_file_view_generator.py
- tasks.py
- tests/integration/commands/export/html/file_traceability/13_file_link_to_a_file_with_empty_first_string/file.py
- tests/integration/commands/export/html/file_traceability/13_file_link_to_a_file_with_empty_first_string/input.sdoc
- tests/integration/commands/export/html/file_traceability/13_file_link_to_a_file_with_empty_first_string/test.itest
> Source file traceability: fix edge case: Pygments ignore the first empty line in a file

- strictdoc/export/html/templates/_helpers/multiline_field.jinja.html
- strictdoc/export/html/templates/_helpers/singleline_field.jinja.html
- strictdoc/export/html/templates/single_document/frame_document_grammar_edit_custom_field.jinja.html
- tests/end2end/document/UC12_edit_document_grammar/UC12_T02_move_field_up/test_UC12_T02_move_field_up.py
- tests/end2end/document/UC12_edit_document_grammar/UC12_T03_move_field_down/test_UC12_T03_move_field_down.py
- tests/end2end/document/UC12_edit_document_grammar/UC12_T04_delete_existing_field/test_UC12_T04_delete_existing_field.py
- tests/end2end/document/UC12_edit_document_grammar/UC12_T11_add_field_move_up_save/test_UC12_T11_add_field_move_up_save.py
- tests/end2end/document/UC12_edit_document_grammar/UC12_T12_add_field_move_up_and_down_save/test_UC12_T12_add_field_move_up_and_down_save.py
...to identify field attributes in tests.
> UI: forms: add a default field_name value for newly added fields 

- strictdoc/export/html/_static/_requirement.css
> UI: Fix table border in Safari

- strictdoc/export/html/_static/_requirement.css
> RST tables: align padding of normal text and padding of bullet list.

- strictdoc/export/html/_static/_element.css
> UI: Fix wrong behavior of UI items in the menu

- strictdoc/cli/cli_arg_parser.py
- strictdoc/server/server.py
> server: create the output in the temporary directory unless specified

- tasks.py
We do not do any cookies / sessions just yet. Hopefully it is ok to reuse. The tests are noticeably much faster.
> tests/end2end: reuse the browser session to speed up the tests

- strictdoc/export/html/_static/_base.css
- strictdoc/export/html/_static/_element.css
- strictdoc/export/html/_static/_layout.css
- strictdoc/export/html/generators/document.py
- strictdoc/export/html/generators/document_deep_trace.py
- strictdoc/export/html/generators/document_table.py
- strictdoc/export/html/generators/document_trace.py
- strictdoc/export/html/generators/document_tree.py
- strictdoc/export/html/generators/requirements_coverage.py
- strictdoc/export/html/generators/source_file_coverage.py
- strictdoc/export/html/generators/source_file_view_generator.py
- strictdoc/export/html/templates/base.jinja.html
> UI: Add StrictDoc label on the generated/server HTML pages

- strictdoc/export/html/form_objects/document_grammar_form_object.py
- strictdoc/server/routers/main_router.py
- tests/end2end/document/UC12_edit_document_grammar/UC12_T13_add_three_fields/expected_output/document.sdoc
- tests/end2end/document/UC12_edit_document_grammar/UC12_T13_add_three_fields/input/document.sdoc
- tests/end2end/document/UC12_edit_document_grammar/UC12_T13_add_three_fields/test_UC12_T13_add_three_fields.py
> server, UI: finish the implementation of saving multiple grammar fields

- tests/end2end/document/UC07_edit_requirement/UC07_T01_editing_requirement/input/document.sdoc
- tests/end2end/document/UC07_edit_requirement/UC07_T01_editing_requirement/test_UC07_T01_editing_requirement.py
- tests/end2end/helpers/screens/document/form_edit_requirement.py
- tests/end2end/helpers/screens/document/screen_document.py
- tests/end2end/helpers/screens/document_tree/screen_document_tree.py
> tests/end2end: introduce screen-based test helpers: UC07_T01

- strictdoc/export/html/_static/requirement.css
> UI: TBL view: fix top border

- tests/end2end/helpers/screens/document_tree/screen_document_tree.py
- tests/end2end/project_options/project_title/01_option_not_specified/test_01_option_not_specified.py
- tests/end2end/project_options/project_title/02_option_specified/test_02_option_specified.py
> tests: end2end updates

- strictdoc/export/html/_static/form.css
- strictdoc/export/html/_static/requirement__temporary.css
> UI: Fix field overflow if text has extra long words

- strictdoc/export/html/_static/form.css
- strictdoc/export/html/templates/components/form/field/file/index.jinja
- strictdoc/export/html/templates/components/form/field/text/index.jinja
> UI: Display multiple validation messages as a list

- tests/end2end/server.py
This enhancement should help in investigating #966.
> tests/end2end: when exception happens, print out and err output to the console

- strictdoc/export/html/templates/_shared/requirement.jinja.html
- strictdoc/export/html/templates/_shared/section.jinja.html
- strictdoc/export/html/templates/components/requirement/index.jinja
- strictdoc/export/html/templates/single_document/frame_document_config.jinja.html
> Static HTML export: remove node reactions on hovering

- strictdoc/export/html/renderers/markup_renderer.py
- strictdoc/server/routers/main_router.py
- tests/end2end/document/UC08_edit_section/UC08_T05_cancel_edit_nested_section/expected_output/document.sdoc
- tests/end2end/document/UC08_edit_section/UC08_T05_cancel_edit_nested_section/input/document.sdoc
- tests/end2end/document/UC08_edit_section/UC08_T05_cancel_edit_nested_section/test_UC08_T05_cancel_edit_nested_section.py
- tests/end2end/helpers/constants.py
> server: handle one case of when editing section is cancelled

- strictdoc/export/html/_static/element.css
- strictdoc/export/html/templates/_shared/document_header.jinja.html
- strictdoc/export/html/templates/_shared/document_title.jinja
- strictdoc/export/html/templates/_shared/source_file_header.jinja.html
> UI: document view header: include document title in turbo-frame

- strictdoc/backend/sdoc/models/document.py
- strictdoc/export/html/_static/content.css
- strictdoc/export/html/_static/node.css
- strictdoc/export/html/_static/requirement.css
- strictdoc/export/html/templates/_shared/document_freetext.jinja.html
- strictdoc/export/html/templates/single_document/frame_document_config.jinja.html
- strictdoc/export/html/templates/single_document_table/document.jinja.html
- strictdoc/export/html/templates/single_document_traceability/document.jinja.html
- strictdoc/export/html/templates/single_document_traceability_deep/document.jinja.html
- tests/integration/commands/export/html/caching_markup/01_caching_does_not_break_markup_of_each_document_type/test.itest
- tests/integration/commands/export/html/markup/01_referencing_a_section_with_LINK/input.sdoc
- tests/integration/commands/export/html/markup/01_referencing_a_section_with_LINK/section.sdoc
- tests/integration/commands/export/html/markup/01_referencing_a_section_with_LINK/test.itest
- tests/integration/html_markup_validator.py
> UI: add placeholder for empty views

- docs/strictdoc_01_user_guide.sdoc
- docs/strictdoc_02_faq.sdoc
- docs/strictdoc_03_development_plan.sdoc
- docs/strictdoc_04_backlog.sdoc
- strictdoc/backend/sdoc/models/document.py
- strictdoc/backend/sdoc/models/free_text.py
- strictdoc/export/html/_static/form.css
- strictdoc/export/html/form_objects/document_config_form_object.py
- strictdoc/server/routers/main_router.py
- tests/end2end/document/UC11_edit_document_config/UC11_T44_freetext_LINK_to_a_section/expected_output/document.sdoc
- tests/end2end/document/UC11_edit_document_config/UC11_T44_freetext_LINK_to_a_section/input/document.sdoc
- tests/end2end/document/UC11_edit_document_config/UC11_T44_freetext_LINK_to_a_section/test_UC11_T44_freetext_LINK_to_a_section.py
Also fix generating [LINK...] links from Document's abstract.
> docs: update Development Plan

- strictdoc/server/server.py
Closes #1011
The fix is ugly but works.
> server: do not reload when anything in tests/ is touched

- tests/end2end/document/document/UC03_create_section/UC03_T01_cancel_new_section/test_UC03_T01_cancel_new_section.py
- tests/end2end/document/document/UC03_create_section/UC03_T02_create_before_section/test_UC03_T02_create_before_section.py
- tests/end2end/document/document/UC03_create_section/UC03_T04_create_two_sibling_sections/test_UC03_T04_create_two_sibling_sections.py
- tests/end2end/document/document/UC03_create_section/UC03_T05_create_three_nested_sections/test_UC03_T05_create_three_nested_sections.py
- tests/end2end/document/document/UC03_create_section/UC03_T06_create_section_after_requirement/test_UC03_T06_create_section_after_requirement.py
- tests/end2end/document/document/UC03_create_section/UC03_T07_create_section_sanitizing_trailing_symbols/test_UC03_T07_create_section_sanitizing_trailing_symbols.py
- tests/end2end/document/document/UC06_create_requirement/UC06_T03_create_requirement_after_section/test_UC06_T03_creating_requirement_after_section.py
- tests/end2end/document/document/UC06_create_requirement/UC06_T04_create_requirement_in_section/test_UC06_T04_create_requirement_in_section.py
- tests/end2end/document/document/UC06_create_requirement/UC06_T06_create_requirements_in_document/test_UC06_T06_create_requirements_in_document.py
- tests/end2end/document/document/UC07_edit_requirement/UC07_G1_editing_requirement_links/UC07_G1_T01_add_one_link/test_UC07_G1_T01_add_one_link.py
- tests/end2end/document/document/UC07_edit_requirement/UC07_G1_editing_requirement_links/UC07_G1_T03_remove_existing_link/test_UC07_G1_T03_remove_existing_link.py
- tests/end2end/document/document/UC07_edit_requirement/UC07_G1_editing_requirement_links/UC07_G1_T13_renaming_uid_when_parent_links_exist/test_UC07_G1_T13_renaming_uid_when_parent_links_exist.py
- tests/end2end/document/document/UC08_edit_section/UC08_T06_cancel_edit_nested_section/test_UC08_T06_cancel_edit_nested_section.py
- tests/end2end/helpers/components/add_node_menu.py
- tests/end2end/helpers/components/node/document_root.py
- tests/end2end/helpers/components/node/node.py
- tests/end2end/helpers/components/node/requirement.py
- tests/end2end/helpers/components/node/section.py
- tests/end2end/helpers/constants.py
- tests/end2end/helpers/screens/screen.py
- pass node_order to Section and Requirement
- pass node_xpath to Node from subclasses
> tests/end2end: Updating the node finding method using testid

- docs/strictdoc_01_user_guide.sdoc
- docs/strictdoc_04_backlog.sdoc
> docs: document the existing capability of UI v0

- strictdoc/export/html/_static/requirement.css
> export/html: Update the backport to a container-type using @media

- docs/sphinx/source/strictdoc_01_user_guide.rst
- docs/sphinx/source/strictdoc_04_backlog.rst
- strictdoc/__init__.py
Also regenerate Read the Docs documentation.
>  Bump version to 0.0.34 

- strictdoc/core/environment.py
> server: resolve paths to assets correctly for PyInstaller

- docs/sphinx/source/strictdoc_01_user_guide.rst
- docs/sphinx/source/strictdoc_02_faq.rst
- docs/strictdoc_01_user_guide.sdoc
> docs: document the lack of non-string types support in the UI

- docs/sphinx/source/strictdoc_01_user_guide.rst
- docs/sphinx/source/strictdoc_03_development_plan.rst
- docs/sphinx/source/strictdoc_30_credits.rst
- docs/strictdoc_01_user_guide.sdoc
- docs/strictdoc_03_development_plan.sdoc
- docs/strictdoc_30_credits.sdoc
> docs: document the IDE support using TextMate grammars

- strictdoc/backend/sdoc/grammar/grammar.py
- strictdoc/backend/sdoc/grammar/type_system.py
- strictdoc/backend/sdoc/models/requirement.py
- tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough.py
> backend/sdoc: disallow empty single fields completely.

- developer/pip_install_strictdoc_deps.py
- tasks.py
> tasks: silently upgrade strictdoc dependencies when needed

- strictdoc/export/html/renderers/markup_renderer.py
- strictdoc/helpers/rst.py
- tasks.py
- tests/end2end/conftest.py
- tests/integration/commands/export/html/rst_markup_to_html/01_table_to_html/input.sdoc
- tests/integration/commands/export/html/rst_markup_to_html/01_table_to_html/test.itest
- tests/unit/strictdoc/helpers/test_rst.py
> export/html: when rendering DTR screen, truncate RST directives to just nothing

- strictdoc/export/html/templates/screens/source_file_view/index.jinja
> export/html: Move nav panel in source_file_view to left

- strictdoc/export/html/_static/requirement.css
> export/html: add bottom margin for requirement content items

- tests/end2end/helpers/components/collapsible_list.py
- tests/end2end/helpers/screens/screen.py
- tests/end2end/navigation/collapsible_list/expected_output/document.sdoc
- tests/end2end/navigation/collapsible_list/input/document.sdoc
- tests/end2end/navigation/collapsible_list/test_UC114_T01_UI_collapsible_list.py
> tests/end2end: implement a test for collapsible list

- pyproject.toml
> pyproject.toml: exclude unneeded dependencies when releasing Pip

- strictdoc/core/document_tree_iterator.py
- strictdoc/core/file_tree.py
- strictdoc/export/html/templates/screens/document/_shared/project_tree.jinja
- strictdoc/export/html/templates/screens/project_index/frame_project_tree.jinja.html
- strictdoc/export/html/templates/screens/source_file_coverage/main.jinja
> export/html: project tree TOC: print full relative paths

- .github/workflows/periodic-release-test.yml
- strictdoc/core/document_finder.py
- strictdoc/core/file_tree.py
- tests/end2end/navigation/collapsible_list/test_UC114_T01_UI_collapsible_list.py
- tests/end2end/navigation/toc/test_UC112_T01_UI_toc.py
> tests/end2end: try to fix flaky test: UC112_T01_UI: sleep 1s to let animations finish 

- strictdoc/core/actions/export_action.py
- strictdoc/core/document_finder.py
- strictdoc/core/document_meta.py
- strictdoc/core/document_tree.py
- strictdoc/core/project_config.py
- strictdoc/core/traceability_index.py
- strictdoc/export/html/document_type.py
- strictdoc/export/html/generators/document.py
- strictdoc/export/html/generators/document_deep_trace.py
- strictdoc/export/html/generators/document_table.py
- strictdoc/export/html/generators/document_trace.py
- strictdoc/export/html/generators/document_tree.py
- strictdoc/export/html/generators/requirements_coverage.py
- strictdoc/export/html/generators/source_file_coverage.py
- strictdoc/export/html/generators/source_file_view_generator.py
- strictdoc/export/html/html_generator.py
- strictdoc/export/html/templates/_shared/nav.jinja.html
- strictdoc/export/html/templates/screens/source_file_coverage/index.jinja
- strictdoc/server/routers/main_router.py
- tests/end2end/helpers/screens/project_index/screen_project_index.py
- tests/end2end/helpers/screens/requirements_coverage/screen_requirements_coverage.py
- tests/end2end/helpers/screens/source_coverage/screen_source_coverage.py
- tests/end2end/requirements_coverage/UC200_view_requirements_coverage/UC200_T01_requirements_coverage/strictdoc.toml
- tests/end2end/requirements_coverage/UC200_view_requirements_coverage/UC200_T01_requirements_coverage/test_UC200_T01_requirements_coverage.py
- tests/end2end/server.py
- tests/end2end/source_coverage/UC250_requirements_to_source_traceability/UC250_T01_view_source_coverage/strictdoc.toml
- tests/end2end/source_coverage/UC250_requirements_to_source_traceability/UC250_T01_view_source_coverage/test_UC250_T01_view_source_coverage.py
- tests/end2end/source_coverage/UC251_source_file/UC251_T01_view_source_file/strictdoc.toml
- tests/end2end/source_coverage/UC251_source_file/UC251_T01_view_source_file/test_UC251_T01_view_source_file.py
- tests/unit/strictdoc/core/test_traceability_index.py
Closes #1032
Closes #1142
Closes #1019
> server: load all document pages on demand

- strictdoc/core/document_iterator.py
- strictdoc/export/html/_static/controllers/collapsible_list_controller.js
- strictdoc/export/html/_static/controllers/draggable_list_controller.js
- strictdoc/export/html/_static/draggable_list.js
- strictdoc/export/html/_static/element.css
- strictdoc/export/html/_static/resizable_bar.js
- strictdoc/export/html/templates/actions/document/move_node/stream_update_document_content.jinja
- strictdoc/export/html/templates/screens/document/_shared/frame_toc.jinja
- strictdoc/export/html/templates/screens/document/document/index.jinja
- strictdoc/server/routers/main_router.py
> export/html: implement draggable_list

- strictdoc/export/html/_static/controllers/collapsible_list_controller.js
- strictdoc/export/html/_static/controllers/deletable_field_controller.js
- strictdoc/export/html/_static/controllers/draggable_list_controller.js
- strictdoc/export/html/_static/controllers/dropdown_menu_controller.js
- strictdoc/export/html/_static/controllers/editable_field_controller.js
- strictdoc/export/html/_static/controllers/modal_controller.js
- strictdoc/export/html/_static/controllers/movable_field_controller.js
- strictdoc/export/html/_static/controllers/scroll_into_view_controller.js
- strictdoc/export/html/templates/screens/document/document/index.jinja
- strictdoc/export/html/templates/screens/document/table/index.jinja
- strictdoc/export/html/templates/screens/document/traceability/index.jinja
- strictdoc/export/html/templates/screens/document/traceability_deep/index.jinja
- strictdoc/export/html/templates/screens/project_index/index.jinja
- tests/end2end/project_options/html_assets_strictdoc_dir/01_option_specified_project_index/document.sdoc
- tests/end2end/project_options/html_assets_strictdoc_dir/01_option_specified_project_index/strictdoc.toml
- tests/end2end/project_options/html_assets_strictdoc_dir/01_option_specified_project_index/test_01_option_specified.py
- tests/end2end/project_options/html_assets_strictdoc_dir/02_option_specified_document/document.sdoc
- tests/end2end/project_options/html_assets_strictdoc_dir/02_option_specified_document/strictdoc.toml
- tests/end2end/project_options/html_assets_strictdoc_dir/02_option_specified_document/test_02_option_specified_document.py
- tests/end2end/project_options/html_assets_strictdoc_dir/03_option_specified_requirements_coverage/document.sdoc
- tests/end2end/project_options/html_assets_strictdoc_dir/03_option_specified_requirements_coverage/strictdoc.toml
- tests/end2end/project_options/html_assets_strictdoc_dir/03_option_specified_requirements_coverage/test_03_option_specified_requirements_coverage.py
> server, export/html: remove last hardcoded path to Stimulus.js

- strictdoc/__init__.py
- strictdoc/server/routers/main_router.py
> main_router: fix move_node action regression due to the recent refactoring

- tasks.py
> tasks: performance task to generate and visualize profiling info

- strictdoc/__init__.py
- strictdoc/core/finders/source_files_finder.py
- tests/integration/commands/export/html/file_traceability/g1_file_types/30_cc/example.sdoc
- tests/integration/commands/export/html/file_traceability/g1_file_types/30_cc/file.cc
- tests/integration/commands/export/html/file_traceability/g1_file_types/30_cc/test.itest
> export/html, source traceability: add support for C++/.cc extension

- strictdoc/export/html/_static/element.css
> export/html: fix TOC styles for disabled items on DTR screen

- strictdoc/export/html/templates/screens/document/_shared/frame_toc.jinja
> export/html: fix margins in DOC TREE

- docs/strictdoc_01_user_guide.sdoc
https://github.com/strictdoc-project/strictdoc/commit/5f2eaaaf59c43e47aaf3fed28d24a49d69061c68
> docs/strictdoc_01_user_guide.sdoc: remove accidental debug lines

- strictdoc/export/html/renderers/markup_renderer.py
- strictdoc/export/html/templates/components/requirement/multiline/index.jinja
- tests/integration/commands/export/html/grammar/02_custom_field_rendered_to_rst/input.sdoc
- tests/integration/commands/export/html/grammar/02_custom_field_rendered_to_rst/test.itest
> export/html: fix RST rendering for custom fields

- tests/end2end/helpers/exception_handler.py
- tests/end2end/helpers/form/form.py
> tests/end2end: start catching Selenium exceptions more targeted

- pyproject.toml
- strictdoc/__init__.py
- strictdoc/backend/reqif/reqif_export.py
- strictdoc/backend/reqif/reqif_import.py
- strictdoc/cli/command_parser_builder.py
- strictdoc/core/actions/export_action.py
- tests/integration/backend/reqif/profiles/p01_sdoc/end_to_end/50_reqifz_basic_roundtrip/sample.sdoc
- tests/integration/backend/reqif/profiles/p01_sdoc/end_to_end/50_reqifz_basic_roundtrip/test.itest
- tests/integration/commands/export/options/--formats/01_incorrect_format/test.itest
> backend/reqif: ReqIFz roundtrip

- strictdoc/export/html/_static/element.css
- strictdoc/export/html/templates/components/node/node_controls/index.jinja
Simplification of menu layout structure for the "Add node" menu
Closes #1661
> export/html: Preparing the menu structure for adding new node types

- strictdoc/export/html/_static/element.css
- strictdoc/export/html/_static/form.css
- strictdoc/export/html/form_objects/document_grammar_form_object.py
- strictdoc/export/html/templates/components/grammar_form/row_with_grammar_element/index.jinja
- strictdoc/export/html/templates/components/grammar_form_element/index.jinja
- strictdoc/server/routers/main_router.py
- tests/end2end/helpers/screens/document/form_edit_grammar.py
- tests/end2end/screens/document/edit_document_grammar_element/edit_grammar_back_button/expected_output/document.sdoc
- tests/end2end/screens/document/edit_document_grammar_element/edit_grammar_back_button/input/document.sdoc
- tests/end2end/screens/document/edit_document_grammar_element/edit_grammar_back_button/test_case.py
> export/html: improve the edit grammar form

- drafts/rst_examples.sdoc
- strictdoc/export/html/_static/autogen.css
- strictdoc/export/html/_static/element.css
- Add 'drafts/rst_examples.sdoc'
- add CSS for admonition markup
Closes #1706
> Styles: add CSS for RST admonition markup

- strictdoc/export/html/_static/controllers/draggable_list_controller.js
> export/html: draggable_list_controller.js: Send a request to the server only if the object actually changes position

- strictdoc/export/html/_static/element.css
- strictdoc/export/html/templates/screens/document/_shared/project_tree.jinja
> export/html: update CSS for project tree on the document page

- strictdoc/export/html/templates/components/node_field/files/index.jinja
- strictdoc/export/html/templates/components/node_field/links/index.jinja
- strictdoc/export/html/templates/components/requirement/index.jinja
Moves relations/files to the bottom of the field block.
Rename labels. 
Closes #2171
> UI: Document: Node: move relations/files to the bottom

- strictdoc/export/html/_static/element.css
- strictdoc/export/html/templates/components/issue/banner.jinja
- strictdoc/export/html/templates/components/issue/index.jinja
- strictdoc/export/html/templates/components/node_field/document_meta/index.jinja
- strictdoc/export/html/templates/components/requirement/index.jinja
- strictdoc/export/html/templates/screens/document/document/frame_document_content.jinja.html
- strictdoc/export/html/templates/screens/document/document/frame_document_issues.jinja
> Add UI for nodes/fields validation messages in document view

- strictdoc/backend/excel/export/excel_generator.py
- strictdoc/backend/sdoc_source_code/models/source_file_info.py
- strictdoc/backend/sdoc_source_code/reader.py
- strictdoc/backend/sdoc_source_code/reader_c.py
- strictdoc/backend/sdoc_source_code/reader_python.py
- strictdoc/core/file_tree.py
- strictdoc/core/project_config.py
- strictdoc/core/source_tree.py
- strictdoc/core/tree_cycle_detector.py
- strictdoc/export/html/renderers/link_renderer.py
- strictdoc/export/json/json_generator.py
- strictdoc/export/spdx/spdx_to_sdoc_converter.py
- strictdoc/helpers/form_data.py
- tests/integration/self_testing/commands/export/01_strictdoc_smoke_test/test.itest
- tests/integration/self_testing/commands/export/04_strictdoc_smoke_test_source_files_from_another_directory/test.itest
This PR addresses one of the #2068 Code Climate tasks: address remaining var-annotated issues.
> code-climate: address remaining var-annotated

- strictdoc/backend/excel/export/excel_generator.py
- strictdoc/backend/reqif/p01_sdoc/sdoc_to_reqif_converter.py
- strictdoc/backend/sdoc/models/document.py
- strictdoc/backend/sdoc/models/node.py
- strictdoc/backend/sdoc/models/object_factory.py
- strictdoc/backend/sdoc/models/section.py
- strictdoc/core/file_traceability_index.py
- strictdoc/core/query_engine/query_object.py
- strictdoc/core/traceability_index_builder.py
- strictdoc/core/transforms/update_grammar_element.py
- strictdoc/export/html/templates/components/node/index.jinja
- strictdoc/export/html/templates/components/node_field/section_h/index.jinja
- strictdoc/export/html/templates/components/node_field/section_h/pdf.jinja
- strictdoc/export/html/templates/components/node_field/section_title/index.jinja
- strictdoc/export/html/templates/screens/document/_shared/toc.jinja
- strictdoc/export/html/templates/screens/document/document/frame_document_content.jinja.html
- strictdoc/export/html/templates/screens/document/pdf/main.jinja
- strictdoc/export/html/templates/screens/document/table/main.jinja
- strictdoc/export/html/templates/screens/document/traceability/main.jinja
- strictdoc/export/html/templates/screens/document/traceability_deep/main.jinja
- strictdoc/export/html/templates/screens/git/diff_content.jinja
- strictdoc/export/html/templates/screens/search/main.jinja
- strictdoc/export/html/templates/screens/traceability_matrix/main.jinja
- strictdoc/export/spdx/spdx_generator.py
- strictdoc/server/routers/main_router.py
- tests/integration/scripting_examples/questionnaires/02_user_provided_example/export_questionnaires.py
This PR addresses the .is_requirement -> .is_requirement() bullet of #2068
> code-climate: remove @property from is_requirement() & co

- strictdoc/backend/sdoc/models/document.py
- strictdoc/export/html/_static/controllers/autocompletable_field_controller.js
- strictdoc/export/html/form_objects/requirement_form_object.py
- strictdoc/export/html/templates/components/form/field/autocompletable/index.jinja
- strictdoc/export/html/templates/components/form/row/row_with_relation.jinja
- strictdoc/export/html/templates/components/form/row/row_with_text_field.jinja
- strictdoc/server/routers/main_router.py
- tests/end2end/helpers/form/form.py
- tests/end2end/helpers/screens/document/form_edit_requirement.py
- tests/end2end/screens/document/create_requirement/_MultipleChoice/create_requirement_MultipleChoice_field_using_autocomplete/expected_output/document.sdoc
- tests/end2end/screens/document/create_requirement/_MultipleChoice/create_requirement_MultipleChoice_field_using_autocomplete/input/document.sdoc
- tests/end2end/screens/document/create_requirement/_MultipleChoice/create_requirement_MultipleChoice_field_using_autocomplete/test_case.py
- tests/end2end/screens/document/update_requirement/_MultipleChoice/update_requirement_MultipleChoice_field_using_autocomplete/expected_output/document.sdoc
- tests/end2end/screens/document/update_requirement/_MultipleChoice/update_requirement_MultipleChoice_field_using_autocomplete/input/document.sdoc
- tests/end2end/screens/document/update_requirement/_MultipleChoice/update_requirement_MultipleChoice_field_using_autocomplete/test_case.py
This PR addresses #2230 MultipleChoice: Allow editing options in the UI using a dropdown menu.
> UI: generalize autocompletion to work for MultipleChoice fields

- strictdoc/backend/reqif/reqif_export.py
- strictdoc/backend/reqif/reqif_import.py
- strictdoc/backend/sdoc/models/type_system.py
- strictdoc/backend/sdoc_source_code/reader.py
- strictdoc/backend/sdoc_source_code/reader_c.py
- strictdoc/backend/sdoc_source_code/reader_python.py
- strictdoc/core/traceability_index_builder.py
- strictdoc/export/html/form_objects/requirement_form_object.py
- strictdoc/export/html/form_objects/rows/row_with_grammar_element_form_object.py
- strictdoc/export/html/generators/view_objects/document_screen_view_object.py
- strictdoc/export/html/tools/html_embedded.py
- strictdoc/export/rst/rst_to_html_fragment_writer.py
- strictdoc/export/spdx/spdx_generator.py
- strictdoc/git/project_diff_analyzer.py
- strictdoc/server/routers/main_router.py
This PR addresses the bullet point "mypy: fix remaining no-redef issues" of the #2068 (code climate) type epic.
> code-climate: mypy: address no-redef

- strictdoc/export/html/_static/controllers/anchor_controller.js
- strictdoc/export/html/_static/element.css
- strictdoc/export/html/_static/node_content.css
- strictdoc/export/html/templates/components/anchor/anchor_clipboard_button.jinja
- strictdoc/export/html/templates/components/anchor/index.jinja
- strictdoc/export/html/templates/components/node/index.jinja
- strictdoc/export/html/templates/rst/anchor.jinja
- strictdoc/export/html/templates/screens/document/document/frame_document_content.jinja.html
> refactor(anchors): move copy/back-links markup from JS to template
