strictdoc-project/strictdoc

strictdoc/export/html/static/document_tree.css
strictdoc/export/html/static/global.css
strictdoc/export/html/static/layout-main-with-toc.css
strictdoc/export/html/static/toc.js
strictdoc/export/html/templates/_shared/requirement.jinja.html
strictdoc/export/html/templates/_shared/table_of_contents.jinja.html
strictdoc/export/html/templates/document_tree/document_tree.jinja.html
strictdoc/export/html/templates/single_document/document.jinja.html
strictdoc/export/html/templates/single_document_table/document.jinja.html
strictdoc/export/html/templates/single_document_traceability/document.jinja.html
strictdoc/export/html/templates/single_document_traceability_deep/document.jinja.html

- sticky document header 
Closes #136 
- make TOC open on page load
- scroll to :target with highlighting
- add `<i>[no title]</i>` for requirements that don't have a title

export/html: TOC and document header improvements, :target highlighting

---

poetry.lock
pyproject.toml
requirements.txt

These 3 packages should be rather stable, so it should be safe to use them with caret.
This should also improve the situation with the security warnings produced by GitHub.

Poetry: use caret "^" for docutils, jinja, and lxml

---

poetry.lock
pyproject.toml
requirements.txt

Thanks for strictdoc, I'm trying it out and really like it so far.
I noticed pygments is a dependency but it's not listed in `pyproject.toml`, which means a pip installation fails unless you also install pygments separately. It's in the `poetry.lock` and `reqirements.txt`, so I guess the CI didn't notice:
```
/tmp$ python3 -m venv venv
/tmp$ source venv/bin/activate
(venv) /tmp$ pip install strictdoc
Collecting strictdoc
Using cached strictdoc-0.0.13-py3-none-any.whl (686 kB)
<snip>
Successfully installed Arpeggio-1.10.2 MarkupSafe-2.0.1 XlsxWriter-1.4.5 beautifulsoup4-4.9.3 docutils-0.16 jinja2-2.11.3 python-datauri-0.2.9 soupsieve-2.2.1 strictdoc-0.0.13 textx-2.3.0
(venv) adam@wizard:/tmp$ strictdoc
Traceback (most recent call last):
File "/tmp/venv/bin/strictdoc", line 5, in <module> …
```

Add pygments to pyproject.toml

---

poetry.lock
pyproject.toml
requirements.txt
strictdoc/backend/reqif/export/sdoc_to_reqif_converter.py
strictdoc/backend/reqif/reqif_export.py
strictdoc/backend/reqif/sdoc_reqif_fields.py
strictdoc/backend/reqif/stage2/fm_studio/mapping.py
strictdoc/backend/reqif/stage2/fm_studio/parser.py
strictdoc/backend/reqif/stage2/native/parser.py
strictdoc/backend/reqif/stage2/native/reqif_to_sdoc_converter.py
tests/integration/reqif/fmStudio/90_SUBSET-026-3-v330/test.itest
tests/integration/reqif/guideline/01_wip_sample/sample.reqif
tests/integration/reqif/guideline/01_wip_sample/test.itest
tests/integration/reqif/native/end_to_end/02_one_requirement/sample.sdoc
tests/integration/reqif/native/end_to_end/03_one_section_one_requirement/sample.sdoc
tests/integration/reqif/native/end_to_end/04_one_section_one_subsection_one_requirement/sample.sdoc
tests/integration/reqif/native/end_to_end/05_two_sections/sample.sdoc
tests/integration/reqif/native/end_to_end/06_three_sections/sample.sdoc
tests/integration/reqif/native/end_to_end/07_one_nested_section/sample.sdoc
tests/integration/reqif/native/end_to_end/08_two_nested_sections/sample.sdoc
tests/integration/reqif/native/end_to_end/09_next_requirement_drop_in_level/sample.sdoc
tests/integration/reqif/native/end_to_end/30_custom_grammar/sample.sdoc
tests/integration/reqif/native/end_to_end/31_custom_grammar_single_choice_type/sample.sdoc
tests/integration/reqif/native/end_to_end/32_custom_grammar_multi_choice_type/sample.sdoc

The following mapping takes place now:
```py
class ReqIFRequirementReservedField(Enum):
UID = "ReqIF.ForeignID"
NAME = "ReqIF.Name"
TEXT = "ReqIF.Text"
class ReqIFChapterField(Enum):
CHAPTER_NAME = "ReqIF.ChapterName"
TEXT = "ReqIF.Text"
```

backend/reqif: make export/import follow some of the ReqIF guideline

---

strictdoc/core/finders/source_files_finder.py
strictdoc/export/html/generators/source_file_view_generator.py
tests/integration/commands/export/html/file_traceability/10_support_files_with_tex_extension/example.sdoc
tests/integration/commands/export/html/file_traceability/10_support_files_with_tex_extension/file.tex
tests/integration/commands/export/html/file_traceability/10_support_files_with_tex_extension/test.itest

requirement references can now be added to latex files as comments. e.g. "% [REQ-001]"

traceability: support linking Tex files to requirements 

---

strictdoc/export/html/_static/_element.css

Improve `_element.css` by adding classes for correct html rendering of ordered non-numeral lists.
Fixes #653.

Code climate: improve css fix html rendering for ordered list

---

strictdoc/backend/sdoc/models/requirement.py
strictdoc/export/html/_static/_requirement.css
strictdoc/export/html/renderers/markup_renderer.py
strictdoc/export/html/templates/_shared/requirement.jinja.html
strictdoc/export/html/templates/_shared/requirement_block/h_title.jinja.html
strictdoc/export/html/templates/_shared/requirement_block/meta.jinja.html
strictdoc/export/html/templates/_shared/requirement_block/multi_line_metas.jinja.html
strictdoc/export/html/templates/_shared/requirement_block/related.jinja.html

1. don't use [no title] when there is a UID (but still no title)
2. don't link to 'UID None' when there is a UID (but still no title)
3. render really long meta fields next to rationale and comments
example before:
example after:

HTML export improvements

---

tests/integration/commands/export/html/file_traceability/05_multiple_files_per_requirement/test.itest

tests/integration: move away from a grep-based test

---

strictdoc/export/html/_static/_layout.css
strictdoc/export/html/templates/base.jinja.html
strictdoc/export/html/templates/single_document/document.jinja.html
strictdoc/export/html/templates/single_document_table/document.jinja.html
strictdoc/export/html/templates/single_document_traceability/document.jinja.html
strictdoc/export/html/templates/single_document_traceability_deep/document.jinja.html

Fixing left panel (TOC) behavior (does not inherit "open-closed" status on pages without a corresponding control)

export/HTML: Fixing left panel (TOC) behavior

---

docs/strictdoc-1-user-manual.sdoc
tests/integration/examples/06_mathjax/example.sdoc

I am coming back to using strictdoc after a wee while away. I remembered that when I added MathJax support in #444, the examples I added required double escaping backslashes in the LaTex.
This was quite annoying, and when I started using strictdoc again this week I decided I'd like to improve it. While investigating this, I realised I should probably learn a bit more about reStructuredText, and discovered the [raw directive](https://docutils.sourceforge.io/docs/ref/rst/directives.html#raw-data-pass-through) which works really well for using latex.
I've updated the examples that use tex to reflect this.

Use raw directive for tex instead of double escaping

---

strictdoc/backend/excel/import_/excel_to_sdoc_converter.py
strictdoc/backend/reqif/import_/reqif_to_sdoc_factory.py
strictdoc/backend/sdoc/grammar/grammar.py
strictdoc/backend/sdoc/models/document_config.py
strictdoc/backend/sdoc/writer.py
strictdoc/export/html/templates/single_document/document.jinja.html
strictdoc/export/html/templates/single_document_table/document.jinja.html
tests/unit/helpers/test_document_builder.py
tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough.py
tests/unit/strictdoc/backend/sdoc/validations/test_requirement.py

Our QA-Manager criticized that the generated requirement documents do not have a confidentiality level classification.
Add optional DocumentConfig CLASSIFICATION field specifying the Document's confidentiality level. 
Added some Unit tests. Found and fixed SDoc-Writer DocumentConfig VERSION<=>UID Sequence.

backend/sdoc/grammar: Add optional DocumentConfig CLASSIFICATION field

---

strictdoc/backend/reqif/export/sdoc_to_reqif_converter.py
strictdoc/backend/sdoc/error_handling.py
strictdoc/backend/sdoc/grammar/grammar.py
strictdoc/backend/sdoc/models/constants.py
strictdoc/backend/sdoc/models/document_grammar.py
strictdoc/backend/sdoc/models/reference.py
strictdoc/backend/sdoc/models/type_system.py
strictdoc/backend/sdoc/validations/requirement.py
strictdoc/backend/sdoc/writer.py
tests/integration/backend/excel/import/01_import_basic_e2e/expected/expected.sdoc
tests/integration/per_document_grammar/validation/06_gef_reference_type_not_allowed/input.sdoc
tests/integration/per_document_grammar/validation/06_gef_reference_type_not_allowed/test.itest
tests/unit/strictdoc/backend/sdoc/test_dsl_grammars.py
tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough.py

Adding ParentReqReference and FileReference TypeValue-Grammar for GRAMMAR-REFS instead of String.
Note: Adding new ExternalReference and updating the Documentation will be done in a separate step.

backend/sdoc/grammar: Add GRAMMAR for REFS-TypeValue variant

---

tests/unit/conftest.py
tests/unit_server/conftest.py

Renaming StrictDoc's base Dirnname breaks pytest and itests.
Trying if conftest.py with only `../../..` works on all platforms.

Code climate: Do not rely on SD working dirname in ConfTest

---

strictdoc/backend/sdoc/models/requirement.py
strictdoc/backend/sdoc/writer.py
strictdoc/export/rst/templates/requirement.jinja.rst
tests/integration/commands/export/rst/08_custom_field/expected/input.rst
tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough.py

backend, sdoc, rst: remove trailing newlines by multistring fields

---

strictdoc/backend/sdoc/models/document.py
strictdoc/backend/sdoc/models/document_config.py
strictdoc/backend/sdoc/models/fragment.py
strictdoc/backend/sdoc/models/fragment_from_file.py
strictdoc/backend/sdoc/models/free_text.py
strictdoc/backend/sdoc/models/reference.py
strictdoc/backend/sdoc/models/requirement.py
strictdoc/backend/sdoc/models/section.py
strictdoc/backend/sdoc/models/type_system.py
strictdoc/backend/source_file_syntax/models/range_pragma.py
strictdoc/backend/source_file_syntax/models/source_file_info.py
strictdoc/core/finders/source_files_finder.py
strictdoc/helpers/auto_described.py
tests/integration/per_document_grammar/validation/06_gef_reference_type_not_allowed/test.itest
tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough.py

The @auto_described implementation saves the effort of writing the custom __str__() descriptions for every class. The generalized implementation should be good enough for now.

Code climate: introduce helpers/auto_described to print objects

---

strictdoc/helpers/string.py
strictdoc/server/routers/main_router.py
tests/end2end/document_tree/UC51_creating_document/UC51_G1_validation/UC51_G1_T03_document_path_with_no_sdoc_extension/test_UC51_G1_T03_document_path_with_no_sdoc_extension.py
tests/end2end/document_tree/UC51_creating_document/UC51_G1_validation/UC51_G1_T04_document_path_bad_chars/test_UC51_G1_T04_document_path_bad_chars.py
tests/unit/strictdoc/helpers/test_string.py

This is a good enough solution for now. Later we can consider adding the .sdoc extension automatically.
Closes #775

server: validation: do not allow creating documents without .sdoc extension

---

strictdoc/cli/main.py

Fixes [issue #837](https://github.com/strictdoc-project/strictdoc/issues/837)

Ensure that multiprocessing.freeze_support() is called in a frozen application

---

strictdoc/export/html/templates/_shared/nav.jinja.html

This feature is very incomplete. We will hide it under a corresponding feature toggle very soon but for now it is better to disable it from being shown by default.

requirements coverage: hide under the traceability flag for now

---

strictdoc/export/html/generators/requirements_coverage.py
strictdoc/export/html/generators/source_file_coverage.py
strictdoc/server/routers/main_router.py

A small clean-up towards https://github.com/strictdoc-project/strictdoc/issues/893.

export/html: remove unused static_path variable from HTML templates

---

docs/strictdoc.toml
strictdoc/cli/cli_arg_parser.py
strictdoc/cli/main.py
strictdoc/core/project_config.py
strictdoc/export/html/generators/document_tree.py
strictdoc/export/html/generators/requirements_coverage.py
strictdoc/export/html/generators/source_file_coverage.py
strictdoc/export/html/generators/source_file_view_generator.py
strictdoc/export/html/html_generator.py
strictdoc/export/html/renderers/link_renderer.py
strictdoc/server/routers/main_router.py
tests/end2end/server.py
tests/integration/options/options_per_project/html_assets_strictdoc_dir/01_option_specified/input.sdoc
tests/integration/options/options_per_project/html_assets_strictdoc_dir/01_option_specified/strictdoc.toml
tests/integration/options/options_per_project/html_assets_strictdoc_dir/01_option_specified/test.itest
tests/integration/options/options_per_project/html_assets_strictdoc_dir/02_option_not_specified/input.sdoc
tests/integration/options/options_per_project/html_assets_strictdoc_dir/02_option_not_specified/test.itest

This helps to have StrictDoc's own assets in the assets/ folder which is the GitHub Pages convention for assets.
Related to #893

strictdoc.toml: introduce the html_assets_strictdoc_dir parameter

---

tests/end2end/conftest.py

This should helps us to understand better where we are when there is a very slow CI job.

tests/end2end: print a test number when a test starts

---

strictdoc/export/html/_static/pan_with_space.js
strictdoc/export/html/templates/single_document_traceability_deep/document.jinja.html

Closes #1016
We had a regression due to the HTML markup changes. The new code seems to work correctly under the scrollable container's overflow: auto.

export/html: improved JS for doing pan over the DTR screen

---

.readthedocs.yaml

The build process is failing with:
```
/usr/bin/python3.6: No module named virtualenv
```

docs: update Read the Docs configuration file

---

strictdoc/server/app.py
strictdoc/server/server.py

From the Python docs: "Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it cannot on Windows)"
The file-like object returned by NamedTemporaryFile can be used to write to the temporary file. The writes must be flushed before another process attempts to read the file.
Also, using an ExitStack removes the need to manually manage the clean-up of the (optional) TemporaryDirectory and NamedTemporaryFile used by `run_strictdoc_server()`.
Closes #1061

server: Do not re-open NamedTemporaryFile on Windows

---

docs/sphinx/source/strictdoc_01_user_guide.rst
docs/strictdoc_01_user_guide.sdoc
strictdoc/backend/sdoc/grammar/grammar.py
strictdoc/backend/sdoc/grammar/type_system.py
strictdoc/backend/sdoc/models/requirement.py
tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough.py

Also, harden section fields in the same way.
Follow-up to: https://github.com/strictdoc-project/strictdoc/issues/823, https://github.com/strictdoc-project/strictdoc/issues/1083

backend/sdoc: disallow empty multiline fields completely.

---

tasks.py
tests/end2end/conftest.py
tests/end2end/project_index/UC56_export_tree_to_reqif/UC56_T01_export_tree_to_reqif/test_UC56_T01_export_tree_to_reqif.py
tests/end2end/screens/document/UC20_export_to_reqif/UC20_T1_green_case/test_UC20_T1_green_case.py
tests/end2end/sdoc_test_environment.py

As it turns out, Tox does not support passing env variables via command line but only via its .tox.ini options file. After we had migrated to Tox, the end2end tests started ignoring the --long-timeouts argument when run on GitHub Actions machines. This patch fixes the --long-timeouts argument by using the custom arguments feature of PyTest.
Closes #1104

tests/end2end: fix --long-timeouts argument

---

strictdoc/export/html/templates/websocket.jinja.html

If `strictdoc server` is being forwarded/tunnelled, it will not necessarily appear to be coming from the client that is configured in the strictdoc conf file. Since the client is already aware of the host/port/protocol that is being used to access the backend, it is possible to construct a suitable websocket URL.

export/html: Connect to websocket relative to current domain

---

strictdoc/export/html/templates/screens/document/document/actions.jinja
strictdoc/export/html/templates/screens/project_index/actions.jinja

braking commit: 7db54d7c40bc5e0eefdc1a0768fc831185549af1

export/html: fix turbo links that were broken by the recent refactoring

---

strictdoc/cli/command_parser_builder.py

The help messages were swapped.

cli/command_parser: Fix 'export' format/field msg

---

strictdoc/backend/sdoc/grammar/type_system.py
tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough.py

allow zero or more whitespace at the start of a multi-line string but still require that it be non-empty

resolve #1210: leading spaces allowed

---

strictdoc/__init__.py
strictdoc/backend/sdoc/error_handling.py
strictdoc/backend/sdoc/grammar/grammar.py
strictdoc/backend/sdoc/writer.py
strictdoc/core/commands/section.py
strictdoc/core/commands/update_document_config.py
strictdoc/export/rst/rst_to_html_fragment_writer.py
tests/end2end/screens/document/cross_cutting/anchors/document/_validations_document/document_create_anchor_broken_rst/expected_output/document.sdoc
tests/end2end/screens/document/cross_cutting/anchors/document/_validations_document/document_create_anchor_broken_rst/input/document.sdoc
tests/end2end/screens/document/cross_cutting/anchors/document/_validations_document/document_create_anchor_broken_rst/test_document_create_anchor_broken_rst.py
tests/end2end/screens/document/cross_cutting/anchors/section/_validations_section/create_section_add_anchor_broken_rst/expected_output/document.sdoc
tests/end2end/screens/document/cross_cutting/anchors/section/_validations_section/create_section_add_anchor_broken_rst/input/document.sdoc
tests/end2end/screens/document/cross_cutting/anchors/section/_validations_section/create_section_add_anchor_broken_rst/test_create_section_add_anchor_broken_rst.py
tests/end2end/screens/document/cross_cutting/anchors/section/_validations_section/update_section_add_anchor_broken_rst/expected_output/document.sdoc
tests/end2end/screens/document/cross_cutting/anchors/section/_validations_section/update_section_add_anchor_broken_rst/input/document.sdoc
tests/end2end/screens/document/cross_cutting/anchors/section/_validations_section/update_section_add_anchor_broken_rst/test_update_section_add_anchor_broken_rst.py
tests/end2end/server.py
tests/unit/strictdoc/backend/sdoc/test_dsl_passthrough.py
tests/unit/strictdoc/backend/sdoc/test_free_text_reader.py
tests/unit/strictdoc/export/rst/directives/test_raw_html_role.py

This change actually makes ANCHOR to be two lines separated with anything that can follow it in FREETEXT.
Also:
tests/end2end/server.py: stop removing log files with every run

grammar, anchors: handle edge case of malformed RST

---

strictdoc/server/routers/main_router.py
tests/end2end/screens/table/UC60_view_document/UC60_T01_document_has_no_content/test_UC60_T01_document_has_no_content.py
tests/end2end/screens/table/UC60_view_document/UC60_T02_document_has_content/test_UC60_T02_document_has_content.py
tests/end2end/screens/traceability/UC30_view_document/UC30_T01_document_has_no_content/test_UC30_T01_document_has_no_content.py
tests/end2end/screens/traceability/UC30_view_document/UC30_T02_document_has_content/test_UC30_T02_document_has_content.py

export/html, server: fix edge case when dropping a req on another req

---

.pylint.ini
strictdoc/backend/sdoc/reader.py
strictdoc/core/actions/passthrough_action.py
strictdoc/core/commands/section.py
strictdoc/core/commands/update_document_config.py
strictdoc/core/commands/update_free_text.py
strictdoc/core/document_finder.py
strictdoc/export/html/form_objects/requirement_form_object.py
strictdoc/export/html/generators/requirements_coverage.py
strictdoc/export/html/generators/source_file_view_generator.py
strictdoc/export/html/html_generator.py
strictdoc/export/html/renderers/markup_renderer.py
strictdoc/export/rst/rst_to_html_fragment_writer.py
strictdoc/server/routers/main_router.py
tests/unit/strictdoc/export/rst/directives/test_raw_html_role.py
tests/unit/strictdoc/export/test_rst_to_html_fragment_writer.py

This ensures that two invocations of StrictDoc running against the same SDoc files will not collide.
The assumption here is that no one will run StrictDoc two times against the same output directory.

backend/sdoc and rst_to_html: take into account the output directory when hashing picked file names

---

strictdoc/backend/sdoc/writer.py
strictdoc/export/html/form_objects/document_grammar_form_object.py
strictdoc/export/html/form_objects/grammar_form_object.py
strictdoc/export/html/form_objects/requirement_form_object.py
strictdoc/export/html/templates/components/form/field/contenteditable/field_with_human_title.jinja
strictdoc/export/html/templates/components/form/field/contenteditable/index.jinja
strictdoc/export/html/templates/components/grammar_form_element/row_with_custom_field/index.jinja
strictdoc/export/html/templates/components/grammar_form_element/row_with_reserved_field/index.jinja
tests/end2end/helpers/screens/document/form_edit_grammar.py
tests/end2end/screens/document/edit_document_grammar_element/edit_grammar_add_human_title/expected_output/document.sdoc
tests/end2end/screens/document/edit_document_grammar_element/edit_grammar_add_human_title/input/document.sdoc
tests/end2end/screens/document/edit_document_grammar_element/edit_grammar_add_human_title/test_case.py
tests/end2end/screens/document/edit_document_grammar_element/edit_grammar_rename_field_human_title/expected_output/document.sdoc
tests/end2end/screens/document/edit_document_grammar_element/edit_grammar_rename_field_human_title/input/document.sdoc
tests/end2end/screens/document/edit_document_grammar_element/edit_grammar_rename_field_human_title/test_case.py

For an example document:
```
[DOCUMENT]
TITLE: TestDoc
OPTIONS:
MARKUP: HTML
[GRAMMAR]
ELEMENTS:
- TAG: REQUIREMENT
FIELDS:
- TITLE: UID
TYPE: String
REQUIRED: False
- TITLE: TITLE
TYPE: String
REQUIRED: False
- TITLE: STATEMENT
TYPE: String
REQUIRED: False
- TITLE: CUSTOM_FIELD
HUMAN_TITLE: Custom Field
TYPE: String
REQUIRED: False
RELATIONS:
- TYPE: Parent
[REQUIREMENT]
UID: REQ-001
TITLE: Test Document
STATEMENT: Test Statement
CUSTOM_FIELD: Test Field
```
We have the following form:
We can edit the human title and after saving, the example document becomes:
```
[DOCUMENT]
TITLE: TestDoc
OPTIONS:
MARKUP: HTML
[GRAMMAR]
ELEMENTS:
- TAG: REQUIREMENT
FIELDS:
- TITLE: UID
TYPE: String
REQUIRED: False
- TITLE: TITLE
TYPE: String
REQUIRED: False
- TITLE: STATEMENT
TYPE: String
REQUIRED: …
```

feat: Make the document grammar editable with respect to human titles

---

strictdoc/export/html/templates/components/node/index.jinja
strictdoc/export/html/templates/components/node/root.jinja
strictdoc/export/html/templates/screens/document/document/index.jinja

that have editing options, i.e: node(index) and root, so that it is not lost on ajax reloading.
Closes #1588

export/html: define the copy_to_clipboard in expandable node components

---

strictdoc/export/html/_static/collapsible_list.js
strictdoc/export/html/_static/element.css
strictdoc/export/html/templates/screens/document/_shared/toc.jinja
strictdoc/export/html/templates/screens/document/document/index.jinja
strictdoc/export/html/templates/screens/document/table/index.jinja
strictdoc/export/html/templates/screens/document/traceability/index.jinja
strictdoc/export/html/templates/screens/document/traceability_deep/index.jinja

Use MutationObserver instead of Stimulus in collapsible_list.js to make it work in static HTML exports
Closes #1097

export/html: make collapsible_list.js based on MutationObserver

---

strictdoc/backend/sdoc/models/document.py
strictdoc/export/html/_static/project_tree.js
strictdoc/export/html/_static/tree.css
strictdoc/export/html/templates/screens/project_index/index.jinja
strictdoc/export/html/templates/screens/project_index/project_tree.jinja

Closes #1709
- Show fragments by default, 
- disable switcher, 
- add info about including file
- update icons
- some improvement in JS (but for now, disable the script)

export/html: project_index: Show fragments by default, disable switcher, add info about including file

---

docs/strictdoc_01_user_guide.sdoc

Strictly following the user guide for this part yield to a crash because the requirement number 2 does not exist.

Fix a crash when following the user guide.

---

strictdoc/export/html2pdf/html2pdf_generator.py

Currently, `strictdoc export --formats html2pdf` proceeds without error or warning even if the HTML2PDF project configuration feature is disabled (which is the current default).
pdf/index.jinja would then not load html2pdf/bundle.js, CSS settings for media print would be missing and thus the resulting PDF will look strange.
This adds a check to fail early instead.

HTML2PDF: Fail early if feature is not enabled

---

docs/strictdoc_01_user_guide.sdoc
strictdoc/export/html/templates/components/requirement/links/index.jinja

This should improve comprehensibility and is consistent to what the rst generator already does.
Also add a sentence in the user documentation to explain by example who in the relation is the parent and who has the active role.

html: Rename "parent relations" to "parents" and "child relations" to "children"

---

strictdoc/backend/sdoc_source_code/reader_python.py
tests/integration/features/file_traceability/_language_parsers/python/04_python_forward_function_in_class/file.py
tests/integration/features/file_traceability/_language_parsers/python/04_python_forward_function_in_class/input.sdoc
tests/integration/features/file_traceability/_language_parsers/python/04_python_forward_function_in_class/test.itest

Makes
```
RELATIONS:
- TYPE: File
VALUE: file.py
FUNCTION: Foo.Bar.baz
```
work for
```py
class Foo:
class Bar:
def baz(self):
pass
```

Forward functions: Search all parent classes

---

strictdoc/server/routers/main_router.py
tests/end2end/helpers/screens/search/search.py
tests/end2end/screens/search/view_search_screen/test_case.py

Shows helpful error messages on the UI for failed search queries.
Before
After:

Report search query error message on UI

---

docs/strictdoc_01_user_guide.sdoc
strictdoc/backend/sdoc_source_code/test_reports/robot_xml_reader.py
strictdoc/core/document_finder.py
strictdoc/export/html/generators/view_objects/helpers.py
tests/integration/features/test_reports/robot_xml/01_basic/input.sdoc
tests/integration/features/test_reports/robot_xml/01_basic/strictdoc.toml
tests/integration/features/test_reports/robot_xml/01_basic/test.itest
tests/integration/features/test_reports/robot_xml/01_basic/test_report/output.robot.xml
tests/integration/features/test_reports/robot_xml/01_basic/tests/feature1a.robot
tests/integration/features/test_reports/robot_xml/01_basic/tests/feature1b.robot
tests/integration/features/test_reports/robot_xml/01_basic/tests/feature2/feature2.robot

This adds test report integration for the Robot Framework native output.xml format.
A new in-memory document is created for the main test suite. All other suites go into sub sections. Section hierarchy follows suite hierarchy.
Every robot test case result is turned into a sdoc node of type `TEST_RESULT` and goes to the section that was created for the parent suite.
`TEST_RESULT` nodes for executed tests are automatically linked through a file function relation to the associated test case in the `*.robot` source code.
`TEST_RESULT` nodes are further automatically linked through a parent/child relation to 1..n requirements. Related requirements are those that were already linked to the test case. The link gets a role Satisfies/IsSatisfiedBy assigned.
Note: Robot Framework could also produce …

Robot Framework part 2: Test report reader

---

strictdoc/backend/sdoc/models/document.py
strictdoc/backend/sdoc/models/document_from_file.py
strictdoc/backend/sdoc/models/model.py
strictdoc/export/html/form_objects/requirement_form_object.py
strictdoc/server/routers/main_router.py
tests/end2end/screens/document/create_requirement/_Tag/create_requirement_Tag_field_using_autocomplete/expected_output/document.sdoc
tests/end2end/screens/document/create_requirement/_Tag/create_requirement_Tag_field_using_autocomplete/input/document.sdoc
tests/end2end/screens/document/create_requirement/_Tag/create_requirement_Tag_field_using_autocomplete/test_case.py
tests/end2end/screens/document/update_requirement/_Tag/update_requirement_Tag_field_using_autocomplete/expected_output/document.sdoc
tests/end2end/screens/document/update_requirement/_Tag/update_requirement_Tag_field_using_autocomplete/input/document.sdoc
tests/end2end/screens/document/update_requirement/_Tag/update_requirement_Tag_field_using_autocomplete/test_case.py

This PR generalises the autocomplete feature to work for "Tag" fields (#2230)
The autocomplete options are collected from the contents of all the same fields of the current document.
I wonder whether we should also allow specifying optional default values in the grammar:
```
- TITLE: TAGS
TYPE: Tag
REQUIRED: False 
- TITLE: TAGS_WITH_DEFAULTS
TYPE: Tag(Derived, Safety-relevant, Security-relevant)
REQUIRED: False 
```
It could help with consistency. Let me know what you think...

UI: autocomplete-for-tags

---

strictdoc/export/html/templates/components/node/readonly.jinja
strictdoc/export/html/templates/components/node_content/index.jinja

Added narrative rules: 
1. Disable **hanging meta** when there is no title.
2. Prevent **node breaks** when there are no multiline fields.
_The 2nd is potentially dangerous if the structure consists only of single-column fields and there are a lot of them (more than 20)._
This is a temporary fix and may still fail in edge cases. A full solution requires upgrading html2pdf to the 0.2.4+ version (currently in development and not yet released), which resolves conflicts between multiple page-break rules. In complex documents with deep nesting or long nodes, multiple active rules can overload the algorithm, resulting in empty pages or page breaks in undesirable places.
Attached is the most layout-intensive document we have so far — its rendering now looks acceptable.
[User Guide - …

fix(html2pdf): Update narrative rules
